### ISSUE TITLE
Compiling "bgi_compiled_script.ksy" reports error

### ISSUE THREAD

**Issue by vollschauer** [mnakamura1337/engine_bgi#2]
I just found your bgi scripts and read you article at kaitai.io ;) And was wondering if it's possible to decompile ._bp files? Since Kaitai Struct and Ruby is new to me, I assume I have to convert the .ksy files to .rb files with the "kaitai-struct-compiler". I works for "bgi_bytecode.ksy" but "bgi_compiled_script.ksy" tells me: 
`/seq/4: unable to find type 'bgi_bytecode', searching from bgi_compiled_script `
Or can you help me out with the ._bp files? Thanks a lot!

**Comment by mnakamura1337** [comment]
I haven't updated these ksy files for a while, and Kaitai Struct develops rapidly ;)
For now, you can just use `--opaque-types=true` option for ksc, and both files should compile just fine.

**Comment by vollschauer** [comment]
Thanks, that worked! But unluckily I can't get any ._bp files decrypted just see a bunch of EOFError's. I guess just not the right game files :) Any chance to PM you?

**Comment by vollschauer** [comment]
I still can't decrypted/decompile my ._bp files, can someone provide a "test" file which is suppose to work... to check if it's even working on my end here? Or could some of your take a look at my files? It would be very helpful since the org. source code is lost :(
